baseurl = "http://haubar.github.io/"
languageCode = "zh-tw"
hasCJKLanguage = true
disqusShortname = ""
googleAnalytics = "UA-9060657-2"
title = "科科的填坑筆記"
copyright = ""


[params]
  googleAutoAds = ""
  avatar = "https://openclipart.org/download/103855/tux.svg"
  author = "Your name"
  info = "Any info about you"

[[menu.main]]
  name = "Github"
  weight = 1
  url = "https://github.com/haubar"

[[menu.main]]
  name = "Website"
  weight = 2
  url = ""

[[menu.main]]
  name = "*Apps*"
  weight = 3
  url = "/apps"

[[menu.main]]
  name = "ABOUT"
  weight = 3
  url = "/about"


[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/haubar"

